/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated.tasks'
import { Route as AuthenticatedShoppingRouteImport } from './routes/_authenticated.shopping'
import { Route as AuthenticatedRecipesRouteImport } from './routes/_authenticated.recipes'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated.inventory'
import { Route as AuthenticatedFinancesRouteImport } from './routes/_authenticated.finances'
import { Route as AuthenticatedDevicesRouteImport } from './routes/_authenticated.devices'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated.calendar'
import { Route as AuthenticatedShoppingScanTicketRouteImport } from './routes/_authenticated.shopping.scan-ticket'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated.settings.notifications'
import { Route as AuthenticatedSettingsLocalizationRouteImport } from './routes/_authenticated.settings.localization'
import { Route as AuthenticatedSettingsFamilyRouteImport } from './routes/_authenticated.settings.family'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShoppingRoute = AuthenticatedShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecipesRoute = AuthenticatedRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinancesRoute = AuthenticatedFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDevicesRoute = AuthenticatedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShoppingScanTicketRoute =
  AuthenticatedShoppingScanTicketRouteImport.update({
    id: '/scan-ticket',
    path: '/scan-ticket',
    getParentRoute: () => AuthenticatedShoppingRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsLocalizationRoute =
  AuthenticatedSettingsLocalizationRouteImport.update({
    id: '/settings/localization',
    path: '/settings/localization',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsFamilyRoute =
  AuthenticatedSettingsFamilyRouteImport.update({
    id: '/settings/family',
    path: '/settings/family',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/recipes': typeof AuthenticatedRecipesRoute
  '/shopping': typeof AuthenticatedShoppingRouteWithChildren
  '/tasks': typeof AuthenticatedTasksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/settings/family': typeof AuthenticatedSettingsFamilyRoute
  '/settings/localization': typeof AuthenticatedSettingsLocalizationRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/shopping/scan-ticket': typeof AuthenticatedShoppingScanTicketRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/recipes': typeof AuthenticatedRecipesRoute
  '/shopping': typeof AuthenticatedShoppingRouteWithChildren
  '/tasks': typeof AuthenticatedTasksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/settings/family': typeof AuthenticatedSettingsFamilyRoute
  '/settings/localization': typeof AuthenticatedSettingsLocalizationRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/shopping/scan-ticket': typeof AuthenticatedShoppingScanTicketRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/devices': typeof AuthenticatedDevicesRoute
  '/_authenticated/finances': typeof AuthenticatedFinancesRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/recipes': typeof AuthenticatedRecipesRoute
  '/_authenticated/shopping': typeof AuthenticatedShoppingRouteWithChildren
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/settings/family': typeof AuthenticatedSettingsFamilyRoute
  '/_authenticated/settings/localization': typeof AuthenticatedSettingsLocalizationRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/shopping/scan-ticket': typeof AuthenticatedShoppingScanTicketRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/devices'
    | '/finances'
    | '/inventory'
    | '/recipes'
    | '/shopping'
    | '/tasks'
    | '/auth/callback'
    | '/settings/family'
    | '/settings/localization'
    | '/settings/notifications'
    | '/shopping/scan-ticket'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/devices'
    | '/finances'
    | '/inventory'
    | '/recipes'
    | '/shopping'
    | '/tasks'
    | '/auth/callback'
    | '/settings/family'
    | '/settings/localization'
    | '/settings/notifications'
    | '/shopping/scan-ticket'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/devices'
    | '/_authenticated/finances'
    | '/_authenticated/inventory'
    | '/_authenticated/recipes'
    | '/_authenticated/shopping'
    | '/_authenticated/tasks'
    | '/auth/callback'
    | '/_authenticated/settings/family'
    | '/_authenticated/settings/localization'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/shopping/scan-ticket'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shopping': {
      id: '/_authenticated/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof AuthenticatedShoppingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes': {
      id: '/_authenticated/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AuthenticatedRecipesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances': {
      id: '/_authenticated/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AuthenticatedFinancesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/devices': {
      id: '/_authenticated/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthenticatedDevicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shopping/scan-ticket': {
      id: '/_authenticated/shopping/scan-ticket'
      path: '/scan-ticket'
      fullPath: '/shopping/scan-ticket'
      preLoaderRoute: typeof AuthenticatedShoppingScanTicketRouteImport
      parentRoute: typeof AuthenticatedShoppingRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/localization': {
      id: '/_authenticated/settings/localization'
      path: '/settings/localization'
      fullPath: '/settings/localization'
      preLoaderRoute: typeof AuthenticatedSettingsLocalizationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/family': {
      id: '/_authenticated/settings/family'
      path: '/settings/family'
      fullPath: '/settings/family'
      preLoaderRoute: typeof AuthenticatedSettingsFamilyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedShoppingRouteChildren {
  AuthenticatedShoppingScanTicketRoute: typeof AuthenticatedShoppingScanTicketRoute
}

const AuthenticatedShoppingRouteChildren: AuthenticatedShoppingRouteChildren = {
  AuthenticatedShoppingScanTicketRoute: AuthenticatedShoppingScanTicketRoute,
}

const AuthenticatedShoppingRouteWithChildren =
  AuthenticatedShoppingRoute._addFileChildren(
    AuthenticatedShoppingRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDevicesRoute: typeof AuthenticatedDevicesRoute
  AuthenticatedFinancesRoute: typeof AuthenticatedFinancesRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedRecipesRoute: typeof AuthenticatedRecipesRoute
  AuthenticatedShoppingRoute: typeof AuthenticatedShoppingRouteWithChildren
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedSettingsFamilyRoute: typeof AuthenticatedSettingsFamilyRoute
  AuthenticatedSettingsLocalizationRoute: typeof AuthenticatedSettingsLocalizationRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDevicesRoute: AuthenticatedDevicesRoute,
  AuthenticatedFinancesRoute: AuthenticatedFinancesRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedRecipesRoute: AuthenticatedRecipesRoute,
  AuthenticatedShoppingRoute: AuthenticatedShoppingRouteWithChildren,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedSettingsFamilyRoute: AuthenticatedSettingsFamilyRoute,
  AuthenticatedSettingsLocalizationRoute:
    AuthenticatedSettingsLocalizationRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
