/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated.tasks'
import { Route as AuthenticatedMedicationsRouteImport } from './routes/_authenticated.medications'
import { Route as AuthenticatedFinancesRouteImport } from './routes/_authenticated.finances'
import { Route as AuthenticatedDevicesRouteImport } from './routes/_authenticated.devices'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated.calendar'
import { Route as AuthenticatedShoppingIndexRouteImport } from './routes/_authenticated.shopping.index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated.settings.index'
import { Route as AuthenticatedRecipesIndexRouteImport } from './routes/_authenticated.recipes.index'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated.inventory.index'
import { Route as AuthenticatedShoppingScanTicketRouteImport } from './routes/_authenticated.shopping.scan-ticket'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated.settings.notifications'
import { Route as AuthenticatedSettingsNavigationRouteImport } from './routes/_authenticated.settings.navigation'
import { Route as AuthenticatedSettingsLocalizationRouteImport } from './routes/_authenticated.settings.localization'
import { Route as AuthenticatedSettingsHomeAssistantRouteImport } from './routes/_authenticated.settings.home-assistant'
import { Route as AuthenticatedSettingsGoogleCalendarRouteImport } from './routes/_authenticated.settings.google-calendar'
import { Route as AuthenticatedSettingsFamilyRouteImport } from './routes/_authenticated.settings.family'
import { Route as AuthenticatedSettingsAppliancesRouteImport } from './routes/_authenticated.settings.appliances'
import { Route as AuthenticatedRecipesPlannerRouteImport } from './routes/_authenticated.recipes.planner'
import { Route as AuthenticatedRecipesDiscoverRouteImport } from './routes/_authenticated.recipes.discover'
import { Route as AuthenticatedRecipesRecipeIdRouteImport } from './routes/_authenticated.recipes.$recipeId'
import { Route as AuthenticatedInventoryScanAddRouteImport } from './routes/_authenticated.inventory.scan-add'
import { Route as AuthenticatedInventoryKitchenRouteImport } from './routes/_authenticated.inventory.kitchen'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicHooksPushSchedulerRouteImport } from './routes/api/public/hooks/push-scheduler'
import { Route as ApiPublicHooksMedicationRemindersRouteImport } from './routes/api/public/hooks/medication-reminders'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMedicationsRoute =
  AuthenticatedMedicationsRouteImport.update({
    id: '/medications',
    path: '/medications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancesRoute = AuthenticatedFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDevicesRoute = AuthenticatedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShoppingIndexRoute =
  AuthenticatedShoppingIndexRouteImport.update({
    id: '/shopping/',
    path: '/shopping/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecipesIndexRoute =
  AuthenticatedRecipesIndexRouteImport.update({
    id: '/recipes/',
    path: '/recipes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShoppingScanTicketRoute =
  AuthenticatedShoppingScanTicketRouteImport.update({
    id: '/shopping/scan-ticket',
    path: '/shopping/scan-ticket',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsNavigationRoute =
  AuthenticatedSettingsNavigationRouteImport.update({
    id: '/settings/navigation',
    path: '/settings/navigation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsLocalizationRoute =
  AuthenticatedSettingsLocalizationRouteImport.update({
    id: '/settings/localization',
    path: '/settings/localization',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsHomeAssistantRoute =
  AuthenticatedSettingsHomeAssistantRouteImport.update({
    id: '/settings/home-assistant',
    path: '/settings/home-assistant',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsGoogleCalendarRoute =
  AuthenticatedSettingsGoogleCalendarRouteImport.update({
    id: '/settings/google-calendar',
    path: '/settings/google-calendar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsFamilyRoute =
  AuthenticatedSettingsFamilyRouteImport.update({
    id: '/settings/family',
    path: '/settings/family',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAppliancesRoute =
  AuthenticatedSettingsAppliancesRouteImport.update({
    id: '/settings/appliances',
    path: '/settings/appliances',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecipesPlannerRoute =
  AuthenticatedRecipesPlannerRouteImport.update({
    id: '/recipes/planner',
    path: '/recipes/planner',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecipesDiscoverRoute =
  AuthenticatedRecipesDiscoverRouteImport.update({
    id: '/recipes/discover',
    path: '/recipes/discover',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecipesRecipeIdRoute =
  AuthenticatedRecipesRecipeIdRouteImport.update({
    id: '/recipes/$recipeId',
    path: '/recipes/$recipeId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryScanAddRoute =
  AuthenticatedInventoryScanAddRouteImport.update({
    id: '/inventory/scan-add',
    path: '/inventory/scan-add',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryKitchenRoute =
  AuthenticatedInventoryKitchenRouteImport.update({
    id: '/inventory/kitchen',
    path: '/inventory/kitchen',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPushSchedulerRoute =
  ApiPublicHooksPushSchedulerRouteImport.update({
    id: '/api/public/hooks/push-scheduler',
    path: '/api/public/hooks/push-scheduler',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMedicationRemindersRoute =
  ApiPublicHooksMedicationRemindersRouteImport.update({
    id: '/api/public/hooks/medication-reminders',
    path: '/api/public/hooks/medication-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/medications': typeof AuthenticatedMedicationsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/inventory/kitchen': typeof AuthenticatedInventoryKitchenRoute
  '/inventory/scan-add': typeof AuthenticatedInventoryScanAddRoute
  '/recipes/$recipeId': typeof AuthenticatedRecipesRecipeIdRoute
  '/recipes/discover': typeof AuthenticatedRecipesDiscoverRoute
  '/recipes/planner': typeof AuthenticatedRecipesPlannerRoute
  '/settings/appliances': typeof AuthenticatedSettingsAppliancesRoute
  '/settings/family': typeof AuthenticatedSettingsFamilyRoute
  '/settings/google-calendar': typeof AuthenticatedSettingsGoogleCalendarRoute
  '/settings/home-assistant': typeof AuthenticatedSettingsHomeAssistantRoute
  '/settings/localization': typeof AuthenticatedSettingsLocalizationRoute
  '/settings/navigation': typeof AuthenticatedSettingsNavigationRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/shopping/scan-ticket': typeof AuthenticatedShoppingScanTicketRoute
  '/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/recipes/': typeof AuthenticatedRecipesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/shopping/': typeof AuthenticatedShoppingIndexRoute
  '/api/public/hooks/medication-reminders': typeof ApiPublicHooksMedicationRemindersRoute
  '/api/public/hooks/push-scheduler': typeof ApiPublicHooksPushSchedulerRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/medications': typeof AuthenticatedMedicationsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/inventory/kitchen': typeof AuthenticatedInventoryKitchenRoute
  '/inventory/scan-add': typeof AuthenticatedInventoryScanAddRoute
  '/recipes/$recipeId': typeof AuthenticatedRecipesRecipeIdRoute
  '/recipes/discover': typeof AuthenticatedRecipesDiscoverRoute
  '/recipes/planner': typeof AuthenticatedRecipesPlannerRoute
  '/settings/appliances': typeof AuthenticatedSettingsAppliancesRoute
  '/settings/family': typeof AuthenticatedSettingsFamilyRoute
  '/settings/google-calendar': typeof AuthenticatedSettingsGoogleCalendarRoute
  '/settings/home-assistant': typeof AuthenticatedSettingsHomeAssistantRoute
  '/settings/localization': typeof AuthenticatedSettingsLocalizationRoute
  '/settings/navigation': typeof AuthenticatedSettingsNavigationRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/shopping/scan-ticket': typeof AuthenticatedShoppingScanTicketRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/recipes': typeof AuthenticatedRecipesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/shopping': typeof AuthenticatedShoppingIndexRoute
  '/api/public/hooks/medication-reminders': typeof ApiPublicHooksMedicationRemindersRoute
  '/api/public/hooks/push-scheduler': typeof ApiPublicHooksPushSchedulerRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/devices': typeof AuthenticatedDevicesRoute
  '/_authenticated/finances': typeof AuthenticatedFinancesRoute
  '/_authenticated/medications': typeof AuthenticatedMedicationsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/inventory/kitchen': typeof AuthenticatedInventoryKitchenRoute
  '/_authenticated/inventory/scan-add': typeof AuthenticatedInventoryScanAddRoute
  '/_authenticated/recipes/$recipeId': typeof AuthenticatedRecipesRecipeIdRoute
  '/_authenticated/recipes/discover': typeof AuthenticatedRecipesDiscoverRoute
  '/_authenticated/recipes/planner': typeof AuthenticatedRecipesPlannerRoute
  '/_authenticated/settings/appliances': typeof AuthenticatedSettingsAppliancesRoute
  '/_authenticated/settings/family': typeof AuthenticatedSettingsFamilyRoute
  '/_authenticated/settings/google-calendar': typeof AuthenticatedSettingsGoogleCalendarRoute
  '/_authenticated/settings/home-assistant': typeof AuthenticatedSettingsHomeAssistantRoute
  '/_authenticated/settings/localization': typeof AuthenticatedSettingsLocalizationRoute
  '/_authenticated/settings/navigation': typeof AuthenticatedSettingsNavigationRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/shopping/scan-ticket': typeof AuthenticatedShoppingScanTicketRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/_authenticated/recipes/': typeof AuthenticatedRecipesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/shopping/': typeof AuthenticatedShoppingIndexRoute
  '/api/public/hooks/medication-reminders': typeof ApiPublicHooksMedicationRemindersRoute
  '/api/public/hooks/push-scheduler': typeof ApiPublicHooksPushSchedulerRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/devices'
    | '/finances'
    | '/medications'
    | '/tasks'
    | '/auth/callback'
    | '/inventory/kitchen'
    | '/inventory/scan-add'
    | '/recipes/$recipeId'
    | '/recipes/discover'
    | '/recipes/planner'
    | '/settings/appliances'
    | '/settings/family'
    | '/settings/google-calendar'
    | '/settings/home-assistant'
    | '/settings/localization'
    | '/settings/navigation'
    | '/settings/notifications'
    | '/shopping/scan-ticket'
    | '/inventory/'
    | '/recipes/'
    | '/settings/'
    | '/shopping/'
    | '/api/public/hooks/medication-reminders'
    | '/api/public/hooks/push-scheduler'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/devices'
    | '/finances'
    | '/medications'
    | '/tasks'
    | '/auth/callback'
    | '/inventory/kitchen'
    | '/inventory/scan-add'
    | '/recipes/$recipeId'
    | '/recipes/discover'
    | '/recipes/planner'
    | '/settings/appliances'
    | '/settings/family'
    | '/settings/google-calendar'
    | '/settings/home-assistant'
    | '/settings/localization'
    | '/settings/navigation'
    | '/settings/notifications'
    | '/shopping/scan-ticket'
    | '/inventory'
    | '/recipes'
    | '/settings'
    | '/shopping'
    | '/api/public/hooks/medication-reminders'
    | '/api/public/hooks/push-scheduler'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/devices'
    | '/_authenticated/finances'
    | '/_authenticated/medications'
    | '/_authenticated/tasks'
    | '/auth/callback'
    | '/_authenticated/inventory/kitchen'
    | '/_authenticated/inventory/scan-add'
    | '/_authenticated/recipes/$recipeId'
    | '/_authenticated/recipes/discover'
    | '/_authenticated/recipes/planner'
    | '/_authenticated/settings/appliances'
    | '/_authenticated/settings/family'
    | '/_authenticated/settings/google-calendar'
    | '/_authenticated/settings/home-assistant'
    | '/_authenticated/settings/localization'
    | '/_authenticated/settings/navigation'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/shopping/scan-ticket'
    | '/_authenticated/inventory/'
    | '/_authenticated/recipes/'
    | '/_authenticated/settings/'
    | '/_authenticated/shopping/'
    | '/api/public/hooks/medication-reminders'
    | '/api/public/hooks/push-scheduler'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiPublicHooksMedicationRemindersRoute: typeof ApiPublicHooksMedicationRemindersRoute
  ApiPublicHooksPushSchedulerRoute: typeof ApiPublicHooksPushSchedulerRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/medications': {
      id: '/_authenticated/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof AuthenticatedMedicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances': {
      id: '/_authenticated/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AuthenticatedFinancesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/devices': {
      id: '/_authenticated/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthenticatedDevicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shopping/': {
      id: '/_authenticated/shopping/'
      path: '/shopping'
      fullPath: '/shopping/'
      preLoaderRoute: typeof AuthenticatedShoppingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/': {
      id: '/_authenticated/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AuthenticatedRecipesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shopping/scan-ticket': {
      id: '/_authenticated/shopping/scan-ticket'
      path: '/shopping/scan-ticket'
      fullPath: '/shopping/scan-ticket'
      preLoaderRoute: typeof AuthenticatedShoppingScanTicketRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/navigation': {
      id: '/_authenticated/settings/navigation'
      path: '/settings/navigation'
      fullPath: '/settings/navigation'
      preLoaderRoute: typeof AuthenticatedSettingsNavigationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/localization': {
      id: '/_authenticated/settings/localization'
      path: '/settings/localization'
      fullPath: '/settings/localization'
      preLoaderRoute: typeof AuthenticatedSettingsLocalizationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/home-assistant': {
      id: '/_authenticated/settings/home-assistant'
      path: '/settings/home-assistant'
      fullPath: '/settings/home-assistant'
      preLoaderRoute: typeof AuthenticatedSettingsHomeAssistantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/google-calendar': {
      id: '/_authenticated/settings/google-calendar'
      path: '/settings/google-calendar'
      fullPath: '/settings/google-calendar'
      preLoaderRoute: typeof AuthenticatedSettingsGoogleCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/family': {
      id: '/_authenticated/settings/family'
      path: '/settings/family'
      fullPath: '/settings/family'
      preLoaderRoute: typeof AuthenticatedSettingsFamilyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/appliances': {
      id: '/_authenticated/settings/appliances'
      path: '/settings/appliances'
      fullPath: '/settings/appliances'
      preLoaderRoute: typeof AuthenticatedSettingsAppliancesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/planner': {
      id: '/_authenticated/recipes/planner'
      path: '/recipes/planner'
      fullPath: '/recipes/planner'
      preLoaderRoute: typeof AuthenticatedRecipesPlannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/discover': {
      id: '/_authenticated/recipes/discover'
      path: '/recipes/discover'
      fullPath: '/recipes/discover'
      preLoaderRoute: typeof AuthenticatedRecipesDiscoverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/$recipeId': {
      id: '/_authenticated/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof AuthenticatedRecipesRecipeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/scan-add': {
      id: '/_authenticated/inventory/scan-add'
      path: '/inventory/scan-add'
      fullPath: '/inventory/scan-add'
      preLoaderRoute: typeof AuthenticatedInventoryScanAddRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/kitchen': {
      id: '/_authenticated/inventory/kitchen'
      path: '/inventory/kitchen'
      fullPath: '/inventory/kitchen'
      preLoaderRoute: typeof AuthenticatedInventoryKitchenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/push-scheduler': {
      id: '/api/public/hooks/push-scheduler'
      path: '/api/public/hooks/push-scheduler'
      fullPath: '/api/public/hooks/push-scheduler'
      preLoaderRoute: typeof ApiPublicHooksPushSchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/medication-reminders': {
      id: '/api/public/hooks/medication-reminders'
      path: '/api/public/hooks/medication-reminders'
      fullPath: '/api/public/hooks/medication-reminders'
      preLoaderRoute: typeof ApiPublicHooksMedicationRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDevicesRoute: typeof AuthenticatedDevicesRoute
  AuthenticatedFinancesRoute: typeof AuthenticatedFinancesRoute
  AuthenticatedMedicationsRoute: typeof AuthenticatedMedicationsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedInventoryKitchenRoute: typeof AuthenticatedInventoryKitchenRoute
  AuthenticatedInventoryScanAddRoute: typeof AuthenticatedInventoryScanAddRoute
  AuthenticatedRecipesRecipeIdRoute: typeof AuthenticatedRecipesRecipeIdRoute
  AuthenticatedRecipesDiscoverRoute: typeof AuthenticatedRecipesDiscoverRoute
  AuthenticatedRecipesPlannerRoute: typeof AuthenticatedRecipesPlannerRoute
  AuthenticatedSettingsAppliancesRoute: typeof AuthenticatedSettingsAppliancesRoute
  AuthenticatedSettingsFamilyRoute: typeof AuthenticatedSettingsFamilyRoute
  AuthenticatedSettingsGoogleCalendarRoute: typeof AuthenticatedSettingsGoogleCalendarRoute
  AuthenticatedSettingsHomeAssistantRoute: typeof AuthenticatedSettingsHomeAssistantRoute
  AuthenticatedSettingsLocalizationRoute: typeof AuthenticatedSettingsLocalizationRoute
  AuthenticatedSettingsNavigationRoute: typeof AuthenticatedSettingsNavigationRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedShoppingScanTicketRoute: typeof AuthenticatedShoppingScanTicketRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
  AuthenticatedRecipesIndexRoute: typeof AuthenticatedRecipesIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedShoppingIndexRoute: typeof AuthenticatedShoppingIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDevicesRoute: AuthenticatedDevicesRoute,
  AuthenticatedFinancesRoute: AuthenticatedFinancesRoute,
  AuthenticatedMedicationsRoute: AuthenticatedMedicationsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedInventoryKitchenRoute: AuthenticatedInventoryKitchenRoute,
  AuthenticatedInventoryScanAddRoute: AuthenticatedInventoryScanAddRoute,
  AuthenticatedRecipesRecipeIdRoute: AuthenticatedRecipesRecipeIdRoute,
  AuthenticatedRecipesDiscoverRoute: AuthenticatedRecipesDiscoverRoute,
  AuthenticatedRecipesPlannerRoute: AuthenticatedRecipesPlannerRoute,
  AuthenticatedSettingsAppliancesRoute: AuthenticatedSettingsAppliancesRoute,
  AuthenticatedSettingsFamilyRoute: AuthenticatedSettingsFamilyRoute,
  AuthenticatedSettingsGoogleCalendarRoute:
    AuthenticatedSettingsGoogleCalendarRoute,
  AuthenticatedSettingsHomeAssistantRoute:
    AuthenticatedSettingsHomeAssistantRoute,
  AuthenticatedSettingsLocalizationRoute:
    AuthenticatedSettingsLocalizationRoute,
  AuthenticatedSettingsNavigationRoute: AuthenticatedSettingsNavigationRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedShoppingScanTicketRoute: AuthenticatedShoppingScanTicketRoute,
  AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
  AuthenticatedRecipesIndexRoute: AuthenticatedRecipesIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedShoppingIndexRoute: AuthenticatedShoppingIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiPublicHooksMedicationRemindersRoute:
    ApiPublicHooksMedicationRemindersRoute,
  ApiPublicHooksPushSchedulerRoute: ApiPublicHooksPushSchedulerRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
